### ISSUE TITLE
Ask trpc-go for RESTful API practices demo

### ISSUE THREAD

**Issue by 44zs44** [Andrew-M-C/trpc-go-utils#1]
Although trpc-go has been open source, beginners still have limited understanding of the content of the document. I want to deeply understand the use of trpc-go through some small demo practices. I don't know if there are such demos.

**Comment by Andrew-M-C** [comment]
@44zs44 I was planning to write some blogs to describe trpc. However, I am quite busy these days... Will do, will do :-)

**Comment by 44zs44** [comment]
Thank you very much for your contribution, maintaining open source is a consuming thing, understand

**Comment by 44zs44** [comment]
When you have time to post articles related to trpc-go, please @ me. This is very important to me

**Comment by Andrew-M-C** [comment]
It will be in Chinese. Is it OK? Or you can send me an email and I can teach you how to.
---- Replied Message ----
| From | ***@***.***> |
| Date | 01/13/2024 11:16 |
| To | Andrew-M-C/trpc-go-utils ***@***.***> |
| Cc | Andrew ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [Andrew-M-C/trpc-go-utils] Ask trpc-go for RESTful API practices demo (Issue #1) |

When you have time to post articles related to trpc-go, please @ me. This is very important to me

**Comment by 44zs44** [comment]
> It will be in Chinese. Is it OK? Or you can send me an email and I can teach you how to. ---- Replied Message ---- | From | ***@***.***> | | Date | 01/13/2024 11:16 | | To | Andrew-M-C/trpc-go-utils ***@***.***> | | Cc | Andrew ***@***.***>, Comment ***@***.***> | | Subject | Re: [Andrew-M-C/trpc-go-utils] Ask trpc-go for RESTful API practices demo (Issue #1) | When you have time to post articles related to trpc-go, please @ me. This is very important to me — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我是Chinese，If it's convenient for you, you can add a wechat: vx2022zhang
